name: Gource visualization

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  gource:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0

      - name: Gource
        uses: nbprojekt/gource-action@57256d303c5a9a5e72ed92ba13e3e83c5ec8b257 # v1.3.0
        with:
          gource_opts: >-
            --max-files 1000
            --key
            -800x600
            --highlight-users
            --filename-time 3
            --output-framerate 25
            -s 0.6
            --multi-sampling
            --auto-skip-seconds 0.1
            --stop-at-end
            --hide mouse,progress

      - name: Upload video
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: the-good-bits-gource
          path: ./gource/gource.mp4
